In [98]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [99]:
df=pd.read_csv('Training set.csv')
df

Unnamed: 0.1  Unnamed: 0  Monthly_Inhand_Salary   Accounts of user  \
0             5279        5279             4377.072500                10   
1              473         473             2184.576667                 8   
2             1355        1355             1837.084167                 3   
3             1546        1546             6867.951667                 5   
4             1323        1323             1089.858750                 4   
...            ...         ...                     ...               ...   
6089          7500        7500             2838.603333                 8   
6090          5966        5966            13239.663330                 2   
6091          3274        3274              636.025000                 6   
6092          2001        2001             5489.962500                 6   
6093          5332        5332             9851.937500                 4   

      Credit cards user have  Interest Rate  Num_of_Loan  Delay_from_due_date  \
0                          6             27            6                   35   
1                          6             32            7                   51   
2                          7              3            2                   14   
3                          4              9            1                    6   
4                          7              4            2                   12   
...                      ...            ...          ...                  ...   
6089                       8             15            3                    5   
6090                       6              6            4                    6   
6091                       8             27            2                   15   
6092                       3              4            1                   24   
6093                       3              3            4                    1   

      Num_of_Delayed_Payment  Changed_Credit_Limit  Outstanding_Debt  \
0                         18                 16.66           2950.80   
1                         19                 25.17           2989.13   
2                          8                  3.37           1336.73   
3                         12                 10.36            625.32   
4                          5                 11.90           1439.09   
...                      ...                   ...               ...   
6089                       9                 12.65           2152.42   
6090                       1                  7.33            187.05   
6091                      10                 11.58           2085.35   
6092                       9                  9.20           1049.75   
6093                       9                 10.96            755.16   

      Total_EMI_per_month  Amount_invested_monthly  Monthly_Balance  \
0              154.172426               301.593795       271.941029   
1              132.481128                71.016720       294.959819   
2               26.746701                31.027274       375.934441   
3               66.457710               176.267359       704.070097   
4               14.350146                50.840361       303.795367   
...                   ...                      ...              ...   
6089            81.038302               168.593275       294.228756   
6090         63191.000000               206.691671      1013.696788   
6091             9.718145                47.990820       295.893534   
6092            49.233888               452.404982       327.357380   
6093           320.742756                96.491754       807.959240   

      Utlization Ratio  Credit Inquiries  Cumulative Balance  Cash Flow  \
0                   76                15                4009       4251   
1                   75                19                2425       1073   
2                   94                 0                1731       3322   
3                   86                 8                1984       1614   
4                   93     

In [100]:
df.isnull().sum()

Unnamed: 0.1               0
Unnamed: 0                 0
Monthly_Inhand_Salary      0
Accounts of user           0
Credit cards user have     0
Interest Rate              0
Num_of_Loan                0
Delay_from_due_date        0
Num_of_Delayed_Payment     0
Changed_Credit_Limit       0
Outstanding_Debt           0
Total_EMI_per_month        0
Amount_invested_monthly    0
Monthly_Balance            0
Utlization Ratio           0
Credit Inquiries           0
Cumulative Balance         0
Cash Flow                  0
Credit Score               0
dtype: int64

No null values are present

In [101]:
df['Credit Score'].unique()

array(['Best', 'Good', 'Standard'], dtype=object)

Here, we can see there are three unique output values.

In [102]:
X=df.iloc[:,:-1].values
y=df.iloc[:,18]
y

0           Best
1           Best
2           Good
3       Standard
4           Good
          ...   
6089        Best
6090        Best
6091    Standard
6092        Best
6093        Best
Name: Credit Score, Length: 6094, dtype: object

Outlier Removal

In [103]:
def cap_data(df):
    for col in df.columns:
        print("capping the ",col)
        if (((df[col].dtype)=='float64') | ((df[col].dtype)=='int64')):
            percentiles = df[col].quantile([0.01,0.99]).values
            df[col][df[col] <= percentiles[0]] = percentiles[0]
            df[col][df[col] >= percentiles[1]] = percentiles[1]
        else:
            df[col]=df[col]
    return df

final_df=cap_data(df)

capping the  Unnamed: 0.1
capping the  Unnamed: 0
capping the  Monthly_Inhand_Salary 
capping the  Accounts of user
capping the  Credit cards user have
capping the  Interest Rate
capping the  Num_of_Loan
capping the  Delay_from_due_date
capping the  Num_of_Delayed_Payment
capping the  Changed_Credit_Limit
capping the  Outstanding_Debt
capping the  Total_EMI_per_month
capping the  Amount_invested_monthly
capping the  Monthly_Balance
capping the  Utlization Ratio
capping the  Credit Inquiries
capping the  Cumulative Balance
capping the  Cash Flow
capping the  Credit Score


C:\Users\nikhi\AppData\Local\Temp\ipykernel_17424\2644200493.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col][df[col] <= percentiles[0]] = percentiles[0]
C:\Users\nikhi\AppData\Local\Temp\ipykernel_17424\2644200493.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col][df[col] >= percentiles[1]] = percentiles[1]


In [104]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20)

In [105]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(X_train)
X_train=scaler.transform(X_train)
X_test=scaler.transform(X_test)

In [106]:
from sklearn.neighbors import KNeighborsClassifier
classifier=KNeighborsClassifier(n_neighbors=5)
classifier.fit(X_train,y_train)

KNeighborsClassifier()

In [107]:
y_pred=classifier.predict(X_test)

c:\Users\nikhi\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [108]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

0.8884331419196062
              precision    recall  f1-score   support

        Best       0.91      0.96      0.94       787
        Good       0.86      0.81      0.83       158
    Standard       0.82      0.72      0.77       274

    accuracy                           0.89      1219
   macro avg       0.87      0.83      0.85      1219
weighted avg       0.89      0.89      0.89      1219

[[757   3  27]
 [ 15 128  15]
 [ 58  18 198]]


Now using entire test set to predict the data

In [109]:
df2=pd.read_csv('Test SET.csv')
df2

Unnamed: 0.1  Unnamed: 0  Monthly_Inhand_Salary   Accounts of user  \
0             7531        7531             3520.621667                 7   
1             1914        1914             2455.479851                 3   
2             1282        1282              592.179167                 6   
3             5517        5517             4976.090000                 9   
4             3610        3610             1720.165833                 7   
...            ...         ...                     ...               ...   
1519          7258        7258            11418.936670                 4   
1520           280         280             2582.813333                 7   
1521          3285        3285             1637.780833                 2   
1522          5567        5567             4622.948333                 5   
1523            51          51             1512.361667                 6   

      Credit cards user have  Interest Rate  Num_of_Loan  Delay_from_due_date  \
0                          6             28            9                   32   
1                          5              5            3                    9   
2                          5             29            3                   41   
3                          7             30            9                   26   
4                          9             32            4                   47   
...                      ...            ...          ...                  ...   
1519                       4             18            2                   30   
1520                       3              5            1                   16   
1521                       5              3            2                    2   
1522                       7             15            4                   26   
1523                       7             17            5                   51   

      Num_of_Delayed_Payment  Changed_Credit_Limit  Outstanding_Debt  \
0                         16                 27.12           4838.26   
1                         16                  9.48            595.94   
2                         22                 -0.34           2688.12   
3                         15                 25.00           3680.62   
4                         19                  7.41           1457.54   
...                      ...                   ...               ...   
1519                      18                 11.19            695.12   
1520                      10                  0.32           1237.46   
1521                       2                  3.58            288.32   
1522                       5                 11.18            112.36   
1523                      18                  9.95           2430.21   

      Total_EMI_per_month  Amount_invested_monthly  Monthly_Balance  \
0              220.401498               120.909497       260.751172   
1              183.764870                48.938091       380.803605   
2                9.575855                46.471450       283.170612   
3              432.581034               298.322639        36.705328   
4               62.671262               100.880899       268.464422   
...                   ...                      ...              ...   
1519           206.557194               550.114615       645.221858   
1520            22.688178               182.033671       323.559484   
1521            30.628576               100.871837       292.277671   
1522           127.790700               184.219006       410.285127   
1523            49.572062                55.298213       306.365891   

      Utlization Ratio  Credit Inquiries  Cumulative Balance  Cash Flow  
0                   85                19                3630       3229  
1                   80                 0                4401       1920  
2                   73                 8                1688       4100  
3                   71                15                4304        402  
4                   89          

In [110]:
#final_df_test=cap_data(df2)

In [111]:
X_test_final=df2.iloc[:,:].values
X_test_final

array([[7531.       , 7531.       , 3520.621667 , ...,   19.       ,
        3630.       , 3229.       ],
       [1914.       , 1914.       , 2455.479851 , ...,    0.       ,
        4401.       , 1920.       ],
       [1282.       , 1282.       ,  592.1791667, ...,    8.       ,
        1688.       , 4100.       ],
       ...,
       [3285.       , 3285.       , 1637.780833 , ...,   18.       ,
        1354.       ,  272.       ],
       [5567.       , 5567.       , 4622.948333 , ...,   16.       ,
        1304.       ,  149.       ],
       [  51.       ,   51.       , 1512.361667 , ...,    8.       ,
        2418.       ,  229.       ]])

In [112]:
y_pred_final=classifier.predict(X_test_final)
y_pred_final

c:\Users\nikhi\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


array(['Best', 'Best', 'Best', ..., 'Best', 'Best', 'Best'], dtype=object)

In [113]:
pd.DataFrame(y_pred_final).to_csv('output.csv')